#!/bin/bash
set -eu

echo "Verifying dependencies"
if ! which pipenv > /dev/null; then
    echo "Installing pipenv..."
    sudo pip3 install pipenv
fi

pipenv update && pipenv lock -r > requirements.txt
