#!/bin/bash

set -e

export PATH=/snap/bin:$PATH

if ! charm whoami > /dev/null; then
    echo "Not logged into charm store" 2>&1
    exit 1
fi


IMAGE_NAME="$CHARM-image"
IMAGE=$(yq r "metadata.yaml" "resources.$IMAGE_NAME.upstream-source")
docker pull "$IMAGE"

URL=$(charm push "$CHARM_BUILD_DIR/$CHARM.charm" "cs:~$NAMESPACE/$CHARM" | yq r - url)
echo "Uploaded: $URL"

IMAGE_REV=$(charm attach cs:~"$NAMESPACE"/"$CHARM" --channel unpublished "$IMAGE_NAME=$IMAGE" | tail -n1 | sed -e 's/uploaded revision \([0-9]*\) of.*/\1/')
echo "Attached: $IMAGE_NAME-$IMAGE_REV"

if [ "$CHANNEL" != unpublished ]; then
   charm release "$URL" --channel "$CHANNEL" --resource "$IMAGE_NAME"-"$IMAGE_REV"
fi
